POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "test2@esksk.com",
  "password": "password123"
}
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDMxNTcsImV4cCI6MTc4NjYwMzQ1N30.MqGtTIj6BIYNgIHhMs0gFfvcijAflco7D8gHwNMu8Kg
###

GET http://localhost:3001/posts?page=1&limit=10&sort=lastest&keyword=수정
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2ODgxNjksImV4cCI6MTc4NjY4ODQ2OX0.MiT-z6YD381xkV-1S-C2K7YAbv_BLkeX-6PUBlT2BXQ
Content-Type: application/json

# {
#   "title": "1번이작성",
#   "content": "1번이작성"
# }

###

GET http://localhost:3001/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODcwMTI5MjUsImV4cCI6MTc4NzAxMzIyNX0.YTSYNwbw1Y_b59nppBR_CXrvHLOdmbX9BsAkeIgRGQ8
Content-Type: application/json

###

POST http://localhost:3001/posts/2/test-views
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODcwMTY5NDQsImV4cCI6MTc4NzAxNzI0NH0.7EMvgOqn6ZJkiMxu3V3uKckOtjZfzObo9W7pCCttfLo
Content-Type: application/json

###

POST http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDc1MTMsImV4cCI6MTc4NjYwNzgxM30.WoRmP2xsdVwjEWc-LE2tB7EQMqjXlYU7oqpMEPgMN-g
Content-Type: application/json

{
  "title": "글등록1",
  "content": "글등록11"
}

###

PATCH http://localhost:3001/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODcwMTI5MjUsImV4cCI6MTc4NzAxMzIyNX0.YTSYNwbw1Y_b59nppBR_CXrvHLOdmbX9BsAkeIgRGQ8
Content-Type: application/json

{
  "title": "456",
  "content": "456"
}

###

GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2Njg1NjgsImV4cCI6MTc4NjY2ODg2OH0.1KOJja_HsaM0GGGQjPADCVO_lklUVvM1ppXwLjutluc
Content-Type: application/json

###

POST http://localhost:3001/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4NzAxMjkyNSwiZXhwIjoxNzg3NjE3NzI1fQ.g8f7_YNzhBQ63dRFCskn-H99hND8slMujMj-B3CuhK8"
}

###

POST http://localhost:3001/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4NjYwODY4MSwiZXhwIjoxNzg3MjEzNDgxfQ.HayDLGwCYrq3ELgLI8mvFM9QNLNpjeF-1XchUeu4x9w"
}



# {
#   "email": "test@test.com",
#   "password": "qlqjs123"
# }