POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "test2@esksk.com",
  "password": "password123"
}
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDMxNTcsImV4cCI6MTc4NjYwMzQ1N30.MqGtTIj6BIYNgIHhMs0gFfvcijAflco7D8gHwNMu8Kg
###

GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDc1MTMsImV4cCI6MTc4NjYwNzgxM30.WoRmP2xsdVwjEWc-LE2tB7EQMqjXlYU7oqpMEPgMN-g
Content-Type: application/json

# {
#   "title": "1번이작성",
#   "content": "1번이작성"
# }

###

GET http://localhost:3001/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDgxMTEsImV4cCI6MTc4NjYwODQxMX0.AgeYSRLoYYCV0Sgex4Q9yTvlAQ1PKRc7AhrvpSU7Bac
Content-Type: application/json

###

POST http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDc1MTMsImV4cCI6MTc4NjYwNzgxM30.WoRmP2xsdVwjEWc-LE2tB7EQMqjXlYU7oqpMEPgMN-g
Content-Type: application/json

{
  "title": "글등록1",
  "content": "글등록11"
}

###

PATCH http://localhost:3001/posts/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDgxMTEsImV4cCI6MTc4NjYwODQxMX0.AgeYSRLoYYCV0Sgex4Q9yTvlAQ1PKRc7AhrvpSU7Bac
Content-Type: application/json

{
  "title": "456",
  "content": "456"
}

###

GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdDJAZXNrc2suY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODY2MDg2ODEsImV4cCI6MTc4NjYwODk4MX0.DepR4e4HODMSxuare1aSLTy2IAP2tKYsi_XjURAXXXg
Content-Type: application/json

###

POST http://localhost:3001/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4NjYwODExMSwiZXhwIjoxNzg3MjEyOTExfQ.NbI4fZSaP2JJCH_nXdBmBsj9HIvbrOPelrDo6v_Z0S8"
}

###

POST http://localhost:3001/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4NjYwODExMSwiZXhwIjoxNzg3MjEyOTExfQ.NbI4fZSaP2JJCH_nXdBmBsj9HIvbrOPelrDo6v_Z0S8"
}



# {
#   "email": "test@test.com",
#   "password": "qlqjs123"
# }